/**
 * Database type definitions for Supabase
 * These will be auto-generated by Supabase CLI later.
 * For now, define the basic structure.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          pin_hash: string;
          weight_kg: number | null;
          height_cm: number | null;
          age: number | null;
          goal: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pin_hash: string;
          weight_kg?: number | null;
          height_cm?: number | null;
          age?: number | null;
          goal?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          pin_hash?: string;
          weight_kg?: number | null;
          height_cm?: number | null;
          age?: number | null;
          goal?: string | null;
          created_at?: string;
        };
      };
      food_logs: {
        Row: {
          id: string;
          user_id: string;
          logged_at: string;
          description: string;
          calories: number | null;
          protein_g: number | null;
          carbs_g: number | null;
          fat_g: number | null;
          meal_type: string | null;
          is_preset: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          logged_at?: string;
          description: string;
          calories?: number | null;
          protein_g?: number | null;
          carbs_g?: number | null;
          fat_g?: number | null;
          meal_type?: string | null;
          is_preset?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          logged_at?: string;
          description?: string;
          calories?: number | null;
          protein_g?: number | null;
          carbs_g?: number | null;
          fat_g?: number | null;
          meal_type?: string | null;
          is_preset?: boolean;
        };
      };
      food_presets: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          calories: number | null;
          protein_g: number | null;
          carbs_g: number | null;
          fat_g: number | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          calories?: number | null;
          protein_g?: number | null;
          carbs_g?: number | null;
          fat_g?: number | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          calories?: number | null;
          protein_g?: number | null;
          carbs_g?: number | null;
          fat_g?: number | null;
        };
      };
      workout_plans: {
        Row: {
          id: string;
          user_id: string;
          day_of_week: number;
          name: string | null;
          exercises: Json;
        };
        Insert: {
          id?: string;
          user_id: string;
          day_of_week: number;
          name?: string | null;
          exercises: Json;
        };
        Update: {
          id?: string;
          user_id?: string;
          day_of_week?: number;
          name?: string | null;
          exercises?: Json;
        };
      };
      workout_logs: {
        Row: {
          id: string;
          user_id: string;
          workout_plan_id: string | null;
          completed_at: string;
          exercises: Json;
          duration_minutes: number | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          workout_plan_id?: string | null;
          completed_at?: string;
          exercises: Json;
          duration_minutes?: number | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          workout_plan_id?: string | null;
          completed_at?: string;
          exercises?: Json;
          duration_minutes?: number | null;
          notes?: string | null;
        };
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          muscle_group: string | null;
          equipment: string | null;
          youtube_video_id: string | null;
          instructions: string | null;
          difficulty: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          muscle_group?: string | null;
          equipment?: string | null;
          youtube_video_id?: string | null;
          instructions?: string | null;
          difficulty?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          muscle_group?: string | null;
          equipment?: string | null;
          youtube_video_id?: string | null;
          instructions?: string | null;
          difficulty?: string | null;
        };
      };
      body_metrics: {
        Row: {
          id: string;
          user_id: string;
          logged_at: string;
          weight_kg: number | null;
          body_fat_percent: number | null;
          waist_cm: number | null;
          chest_cm: number | null;
          arm_cm: number | null;
          thigh_cm: number | null;
          neck_cm: number | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          logged_at?: string;
          weight_kg?: number | null;
          body_fat_percent?: number | null;
          waist_cm?: number | null;
          chest_cm?: number | null;
          arm_cm?: number | null;
          thigh_cm?: number | null;
          neck_cm?: number | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          logged_at?: string;
          weight_kg?: number | null;
          body_fat_percent?: number | null;
          waist_cm?: number | null;
          chest_cm?: number | null;
          arm_cm?: number | null;
          thigh_cm?: number | null;
          neck_cm?: number | null;
        };
      };
      progress_photos: {
        Row: {
          id: string;
          user_id: string;
          uploaded_at: string;
          photo_url: string | null;
          pose_type: string | null;
          ai_analysis: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          uploaded_at?: string;
          photo_url?: string | null;
          pose_type?: string | null;
          ai_analysis?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          uploaded_at?: string;
          photo_url?: string | null;
          pose_type?: string | null;
          ai_analysis?: string | null;
        };
      };
      water_logs: {
        Row: {
          id: string;
          user_id: string;
          logged_at: string;
          amount_ml: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          logged_at?: string;
          amount_ml: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          logged_at?: string;
          amount_ml?: number;
        };
      };
      supplement_logs: {
        Row: {
          id: string;
          user_id: string;
          logged_at: string;
          supplement_name: string;
          taken: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          logged_at?: string;
          supplement_name: string;
          taken?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          logged_at?: string;
          supplement_name?: string;
          taken?: boolean;
        };
      };
      sleep_logs: {
        Row: {
          id: string;
          user_id: string;
          logged_at: string;
          hours_slept: number | null;
          quality: number | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          logged_at?: string;
          hours_slept?: number | null;
          quality?: number | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          logged_at?: string;
          hours_slept?: number | null;
          quality?: number | null;
        };
      };
      user_stats: {
        Row: {
          id: string;
          user_id: string;
          xp: number;
          level: number;
          workout_streak: number;
          logging_streak: number;
          badges: Json;
        };
        Insert: {
          id?: string;
          user_id: string;
          xp?: number;
          level?: number;
          workout_streak?: number;
          logging_streak?: number;
          badges?: Json;
        };
        Update: {
          id?: string;
          user_id?: string;
          xp?: number;
          level?: number;
          workout_streak?: number;
          logging_streak?: number;
          badges?: Json;
        };
      };
      personal_records: {
        Row: {
          id: string;
          user_id: string;
          exercise_id: string;
          weight_kg: number;
          achieved_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          exercise_id: string;
          weight_kg: number;
          achieved_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          exercise_id?: string;
          weight_kg?: number;
          achieved_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
